openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
servers:
  - url: https://nodejs-hw-mongodb-5-4r2f.onrender.com
  - url: http://localhost:3000
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/get.yaml
    post:
      $ref: ../swagger/paths/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/{contactId}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
